<div class="left-shippingrates">
	<p>SHIPPING RATES</p>
	<div class="shipping_holder">
	<div id="shipping_asia" class="shipping_country_holder">
	<div class="shipping_country">Asia</div>
	<div class="shipping_price">FREE</div>
	<div class="shipping_time">2-4days</div>
	</div>
	<div id="shipping_australia" class="shipping_country_holder">
	<div class="shipping_country">Australia</div>
	<div class="shipping_price">FREE</div>
	<div class="shipping_time">3-5days</div>
	</div>
	<div id="shipping_canada" class="shipping_country_holder">
	<div class="shipping_country">Canada</div>
	<div class="shipping_price">FREE</div>
	<div class="shipping_time">2-4days</div>
	</div>
	<div id="shipping_eu" class="shipping_country_holder">
	<div class="shipping_country">EU</div>
	<div class="shipping_price">FREE</div>
	<div class="shipping_time">3-5days</div>
	</div>
	<div id="shipping_india" class="shipping_country_holder">
	<div class="shipping_country">India</div>
	<div class="shipping_price">FREE</div>
	<div class="shipping_time">3-5days</div>
	</div>
	<div id="shipping_indonesia" class="shipping_country_holder">
	<div class="shipping_country">Indonesia</div>
	<div class="shipping_price">FREE</div>
	<div class="shipping_time">2-4days</div>
	</div>
	<div id="shipping_newzealand" class="shipping_country_holder">
	<div class="shipping_country">New Zealand</div>
	<div class="shipping_price">FREE</div>
	<div class="shipping_time">3-5days</div>
	</div>
	<div id="shipping_russia" class="shipping_country_holder">
	<div class="shipping_country">Russia</div>
	<div class="shipping_price">FREE</div>
	<div class="shipping_time">3-5days</div>
	</div>
	<div id="shipping_us" class="shipping_country_holder">
	<div class="shipping_country">US</div>
	<div class="shipping_price">FREE</div>
	<div class="shipping_time">2-4days</div>
	</div>
	<div id="shipping_singapore" class="shipping_country_holder">
	<div class="shipping_country">Singapore</div>
	<div class="shipping_price">FREE</div>
	<div class="shipping_time">2-4days</div>
	</div>
	<div id="shipping_malaysia" class="shipping_country_holder">
	<div class="shipping_country">Malaysia</div>
	<div class="shipping_price">FREE</div>
	<div class="shipping_time">2-4days</div>
	</div>
	<div id="shipping_thailand" class="shipping_country_holder">
	<div class="shipping_country">Thailand</div>
	<div class="shipping_price">FREE</div>
	<div class="shipping_time">2-4days</div>
	</div>
	<br />
	<p id="shipping_notice">Items will be shipped via fedex with a tracking number.</p>
	</div>
</div>