<?php
$shopbybrands = Mage::getResourceModel('shopbybrand/brand_collection')
	                ->setStoreId(0)
	                ->addFieldToFilter('status', array('eq' => 1));
?>
<?php if ($shopbybrands): ?>
	<ul>
		<?php foreach ($shopbybrands as $brand): ?>
			<li>
				<a href="<?php echo $this->getUrl().$brand->getData('url_key')?>">
					<p class="cover">
						<?php
							$path = 'brands' . DS . 'thumbnail'.DS.$brand->getData('brand_id');
							$img = Mage::helper('shopbybrand/image')->init($brand, $path)->resizeThumbnail(175,175);
						?>
						<img src="<?php echo $img ?>"/>
					</p>
					<p class="description">
						<strong class="brand-title"><?php echo $brand->getData('name') ?></strong><br/>
						<?php echo $this->__($brand->getData('short_description')) ?>
					</p>
				</a>
			</li>	
		<?php endforeach ?>
		<div style="clear: both;"></div>
	</ul>
<?php endif ?>
<script type="text/javascript">
jQuery(document).ready(function(){
	jQuery('.homepage-brand .cover').hover(function(){
		jQuery(this).css('opacity','0.1');
		jQuery(this).parent().find('.description').css('opacity','1');
	},function(){
		jQuery(this).css('opacity','1');
		jQuery(this).parent().find('.description').css('opacity','0');
	});
	jQuery('.homepage-brand .description').hover(function(){
		jQuery(this).css('opacity','1');
		jQuery(this).parent().find('.cover').css('opacity','0.1');
	})
});
</script>